wirecard/oxid-ee

- .travis.yml
* Adds Travis configuration to enable running code analysis & style checks on CI.
* _.travis.yml_ has been validated using the Travis CLI ✔️
The following items will be handled in a follow-up PR:
* Utilization of the OXID testing library
* Automated releases & release notes
* https://jira.parkside.at/browse/WDPD-75
> WDPD-75 Add Travis configuration for testing

- Core/OxidEE_Events.php
- Core/Transaction.php
- Extend/Payment_Gateway.php
* adds transaction table in the database
* adds Oxid's magic getter for transaction database table
* extends Oxid's order database table
WDPD-86: https://jira.parkside.at/browse/WDPD-86
> WDPD-86 Transaction table

- menu.xml
- views/admin/de/wirecardpaymentgateway_de_lang.php
- views/admin/en/wirecardpaymentgateway_en_lang.php
* removes the "Wirecard Configuration" -> "Payment Methods" side menu
* https://jira.parkside.at/browse/WDPD-81
> WDPD-81 Adapt side menu

- Extend/Payment_Gateway.php
Addresses transaction detail.
purchase an item with Wirecard Paypal and verify with the " Request body:" debug output in the logs
> WDPD-20 order details

- out/blocks/wd_admin_payment_main_form.tpl
* adds color indication whether the payment method credentials are valid
* enable the module through the shop's admin interface
* go to "Shop Settings" -> "Payment Methods" and select a Wirecard payment method
* click on "Test credentials" button, with the default credentials the text "Merchant configuration was successfully tested." should appear in green color
* when a letter is added to the "HTTP User" or "HTTP Password" field, the text "Test failed, please check your credentials." should appear in red color after clicking the button again
* when any kind of path is added to the "Wirecard Server Address" field (e.g. "https://api-test.wirecard.com/test"), then the same error text as before should appear
* https://jira.parkside.at/browse/WDPD-18
> WDPD-18 Basic payment method configuration

- Extend/Payment_Gateway.php
Add a description to `getDescriptor`
> WDPD-20 Adjust php doc for `getDescriptor`

- Core/BasketHelper.php
- Extend/Basket.php
- Extend/Payment_Gateway.php
- Tests/Unit/Core/BasketHelperTest.php
- metadata.php
- translations/de/wirecardpaymentgateway_de_lang.php
- translations/en/wirecardpaymentgateway_en_lang.php
* add basket handling with discounts
* also adds wrapping, gift cards, etc. to the basket
* get sure to enable everything a basket can contain
* Packaging
* gift card
* shipping costs
* payment costs
go through the whole purchase flow with Paypal and see the request includes all those fields.
https://jira.parkside.at/browse/WDPD-19
https://jira.parkside.at/browse/WDPD-99
> WDPD-19 Create basket items

- Controller/NotifyHandler.php
- Core/OxidEE_Events.php
- Extend/Controller/OrderController.php
- Extend/Controller/ThankYouController.php
- Extend/Model/Basket.php
- Extend/Model/Order.php
- Extend/Model/Payment_Gateway.php
- Extend/View_Config.php
- Model/Transaction.php
- Tests/Unit/Extend/View_Config_Test.php
- default_payment_config.xml
- metadata.php
- out/blocks/checkout_errors.tpl
- out/blocks/profiling_tags.tpl
- out/blocks/wd_admin_order_list_filter.tpl
- out/blocks/wd_admin_order_list_item.tpl
- out/blocks/wd_admin_order_list_sorting.tpl
- phpcs.xml
- views/admin/tpl/transaction_list.tpl
- views/blocks/accountorder.tpl
- views/blocks/accountorder_azure.tpl
- views/blocks/thankyou.tpl
* Shows the user an information if the Wirecard PayPal payment was a success or not
* Fixes the issue with Oxid redirect and getting back to the "Thank you" page
* Login to the admin
* Go to Extensions → Modules and activate Wirecard Oxid EE Paymentgateway
* Go to Shop Settings → Payment Methods
* Find Wirecard PayPal and set it to active
* Go to frontend and make a Wirecard Paypal payment
* You are then redirected to PayPal and depending of the payment success/cancel/error, you are redirected to the correct page back in the Oxid shop
* https://jira.parkside.at/browse/WDPD-23
> WDPD-23 Handle PayPal response

- Controller/NotifyHandler.php
* Converts the timestamp from the notification response to the shops timezone before saving it to the db
* Buy something with wirecard paypal method, check dates in db or order table
https://jira.parkside.at/browse/WDPD-108
> WDPD-108: Convert response timestamp

- Controller/NotifyHandler.php
- Extend/Controller/Admin/OrderList.php
- Extend/Model/Order.php
- Extend/Model/Payment_Gateway.php
- Model/Payment_Method.php
- out/blocks/wd_admin_order_list_filter.tpl
- out/blocks/wd_admin_order_list_item.tpl
- out/blocks/wd_admin_order_list_sorting.tpl
* Add payment method to order table
* Resolve adapt order table problem without additional infos
* Check order table if payment column is added
* Buy something with wirecard paypal, check tables if everything is correct
- Fixes
> WDPD-24: Adds payment method to order table, adapt order handling

- Extend/Controller/OrderController.php
- Extend/Model/Payment_Gateway.php
Adjust `FailureResponse` handling
> WDPD-24 Response handling

- .bin/phraseapp/wd-project.rb
- Rakefile
- Improves PhraseApp scripts by allowing insignificant diffs (keys present in PhraseApp but missing in project)
> WDPD-80: Improve PhraseApp integration

- Controller/Admin/Order/OrderTab.php
- Controller/Admin/TransactionList.php
- Controller/NotifyHandler.php
- Core/AccountHolderHelper.php
- Core/Helper.php
- Core/OrderHelper.php
- Core/OxidEEEvents.php
- Core/PaymentMethodFactory.php
- Core/PaymentMethodHelper.php
- Core/ResponseHandler.php
- Extend/Controller/Admin/PaymentMain.php
- Extend/Controller/OrderController.php
- Extend/Model/Basket.php
- Extend/Model/Order.php
- Extend/Model/PaymentGateway.php
- Model/CreditCardPaymentMethod.php
- Model/PaymentMethod.php
- Tests/Unit/Core/HelperTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
- Tests/Unit/Model/PaypalPaymentMethodTest.php
- Tests/Unit/Model/SofortPaymentMethodTest.php
- out/js/credit_card_form.js
- views/blocks/checkout_errors.tpl
* Displays errors returned from the paymentSDK in the payment step of the checkout process
* Displays error from check checkout form in javascript
* refactor response handling
* https://jira.parkside.at/browse/WDPD-98
> WDPD-98 Display paymentSDK error

- Core/OrderHelper.php
- metadata.php
handle correct backend service
https://jira.parkside.at/browse/WDPD-34
> WDPD-34 correct backend service

- Extend/Controller/OrderController.php
- composer.json
- out/js/credit_card_form.js
* handle next step for non-redirect orders
https://jira.parkside.at/browse/WDPD-34
> WDPD-34 handle next step

- Extend/Model/PaymentGateway.php
* Pass current user language to notify handler URL
* Merchant / customer emails should have proper language in the whole template
* Setup SMTP and email Adresses in Master Oxid settings
* Create customer order and pay
* Emails should be translated in the language customer used while checkout
> WDPD-33 Notify handler language

- Core/Helper.php
- Extend/Model/PaymentGateway.php
- Model/PaymentMethod.php
Add header fields with shop system, shop version, plugin name and plugin version
https://jira.parkside.at/browse/WDPD-119
> WDPD-119 add header fields

- Extend/Controller/OrderController.php
- out/css/spinner.css
- out/js/credit_card_form.js
- views/blocks/wirecard_credit_card_fields.tpl
* reloads the credit card form after an error response was returned from the PaymentGateway
* adds a loading spinner while the credit card form is being loaded
* uses the correct base URL for getting the credit card form
* https://jira.parkside.at/browse/WDPD-116
> WDPD-116 Reload credit card form after error

- .travis.yml
- composer.json
- composer.lock
- Adds missing Symfony Yaml component (dependency of the release script)
- Adjusts Travis config to install dependencies before release
> WDPD-75: Update configuration for release scripts

- Core/OxidEEEvents.php
* Removes the OXID_ENVIRONMENT variable
* Code refactoring
> WDPD-127: Remove OXID_ENVIRONMENT variable

- Extend/Controller/OrderController.php
* Adjusts the name of a class variable in the module's `OrderController`
* https://jira.parkside.at/browse/WDPD-139
> WDPD-139 Rename protected OXID-internal variable name in OrderController

- Controller/Admin/TransactionList.php
- Core/OxidEeEvents.php
- Extend/ListModel.php
- phpcs/Custom/Sniffs/NamingConventions/HungarianNotationVariableNameSniff.php
- views/admin/tpl/transaction_list.tpl
In the transaction's table, we need a sortable row, that's now the `TRANSACTIONNUMBER`
We change the sort order for the transactions table do be descending.
> WDPD-135 add transaction number to have a nice sortable row

- Core/ResponseHandler.php
* improves response handling for non-3DS credit card transactions when the Azure theme is activated
* https://jira.parkside.at/browse/WDPD-137
> WDPD-137 Improve response handling for non-3DS CC transactions in Azure

- views/admin/tpl/transaction_list.tpl
When clicking on the transaction number, it should show the transaction overview.
> WDPD-135 handle transaction number click correctly

- Core/ResponseHandler.php
* checks if a transaction with the same ID already exists in the database and does not save it again in this case.
* https://jira.parkside.at/browse/WDPD-142
> WDPD-142 Add check if transaction ID already exists in transactions table

- Controller/Admin/Order/OrderTabTransactions.php
* Removes action column from order transaction table.
* https://jira.parkside.at/browse/WDPD-146
> WDPD-146 Remove action column from order transaction table

- default_payment_config.xml
Refine the payment sorting according to the index in the list of https://document-center.wirecard.com/display/PTD/Non+Credit+Card
https://jira.parkside.at/browse/WDPD-121
> WDPD-121 Refine sort order

- Core/OxidEeEvents.php
- Core/ResponseHandler.php
- Model/Transaction.php
* adds a unique index to the transaction ID column
* https://jira.parkside.at/browse/WDPD-152
> WDPD-152 Add unique index to transaction ID column

- Tests/Acceptance/SofortCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
* Adds Sofort. checkout tests
* Run `rake runtests_selenium` and check if all tests succeed
* For information on how to see the Selenium tests being run in the browser, follow the instructions in this PR: https://github.com/wirecard/oxid-ee/pull/79
* WDPD-132: https://jira.parkside.at/browse/WDPD-132
> WDPD-132: Create Selenium Happy Flow Tests for Sofort.

- Controller/Admin/Transaction/TransactionTabPostProcessing.php
- Tests/Unit/Controller/Admin/Transaction/TransactionTabPostProcessingTest.php
- out/css/wirecard_wdoxidee_common.css
- views/admin/blocks/wd_admin_payment_main_form.tpl
- views/admin/tpl/tab_post_processing.tpl
* adds a common style to all admin area error messages of the module
* https://jira.parkside.at/browse/WDPD-147
> WDPD-147 Use unified style for admin area error messages

- Controller/FormInteractionController.php
- out/css/wirecard_wdoxidee_spinner.css
- out/js/wirecard_wdoxidee_credit_card_form.js
- views/blocks/wirecard_credit_card_fields.tpl
- views/form_interaction.tpl
add a loading spinner to the redirect page
https://jira.parkside.at/browse/WDPD-148
> WDPD-148 redirect loading spinner

- Core/Helper.php
- Core/OxidEeEvents.php
- Core/PaymentMethodHelper.php
- out/css/wirecard_wdoxidee_modal.css
- views/blocks/sepa_mandate.tpl
* adds initial SEPA mandate text to database while inserting SEPA Direct Debit payment method
* merchant is able to change this text in admin panel
* https://jira.parkside.at/browse/WDPD-150
> WDPD-150 Prefill SEPA mandate text

- Tests/Acceptance/SepaDirectDebitCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
* Adds SEPA Direct Debit checkout tests for purchase/authorization actions
* Adds SEPA Direct Debit checkout tests for with and without BIC
* Run `rake runtests_selenium` and check if all tests succeed
* For information on how to see the Selenium tests being run in the browser, follow the instructions in this PR: https://github.com/wirecard/oxid-ee/pull/79
* WDPD-133: https://jira.parkside.at/browse/WDPD-133
> WDPD-133: Create Selenium Happy Flow Tests for SEPA Direct Debit

- views/admin/blocks/wd_admin_order_list_filter.tpl
- views/admin/blocks/wd_admin_order_list_sorting.tpl
* improves the sorting behaviour for the payment type column in the order table
* https://jira.parkside.at/browse/WDPD-157
> WDPD-157 Improve sorting behaviour for payment type in order table

- .bin/phraseapp/translation-builder.rb
Update the Phraseapp script to handle the new `translate` function signature.
> Update Phraseapp Script

- Core/Helper.php
- Extend/Model/PaymentGateway.php
- Extend/ViewConfig.php
- Model/RatepayInvoicePaymentMethod.php
- Tests/Unit/Core/HelperTest.php
- Tests/Unit/Extend/Model/PaymentGatewayTest.php
- Tests/Unit/Extend/ViewConfigTest.php
- views/blocks/profiling_tags.tpl
Add special fraud protection handling for Ratepay.
- Before going to the checkout page, open the developer console.
- Check the network to load a `di.js` with a unique token in front in the path.
- Do a purchase.
- Check the request `device - fingerprint` should be the same unique token.
https://jira.parkside.at/browse/WDPD-177
> WDPD-177 Ratepay fraud protection

- Extend/Model/PaymentGateway.php
- Model/GiropayPaymentMethod.php
- Model/PaymentMethod.php
- Model/RatepayInvoicePaymentMethod.php
- Model/SepaDirectDebitPaymentMethod.php
- Tests/Unit/Model/GiropayPaymentMethodTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
- Tests/Unit/Model/SepaDirectDebitPaymentMethodTest.php
* Adds mandatory transaction data for Guaranteed Invoice
* https://jira.parkside.at/browse/WDPD-178
> WDPD-178 Additional data for Guaranteed Invoice

- Tests/Acceptance/CheckoutTestCase.php
- Tests/Acceptance/RatepayInvoiceCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
- Tests/Acceptance/inc/mock-data.json
* Adds Selenium tests for **Guaranteed Invoice by Wirecard**:
* Users with a full profile (date of birth & phone number)
* Users without a full profile (date of birth & phone number)
* Run `rake runtests_selenium` and check if all tests succeed
* For information on how to see the Selenium tests being run in the browser, follow the instructions in this PR: https://github.com/wirecard/oxid-ee/pull/79
* WDPD-180: https://jira.parkside.at/browse/WDPD-180
> WDPD-180: Guaranteed Invoice by Wirecard Selenium Happy Flow Tests

- Model/EpsPaymentMethod.php
* Adds missing OXID configuration fields for eps payment method in admin panel (Price, Selected, Sorting)
* https://jira.parkside.at/browse/WDPD-186
> WDPD-186 Add missing eps config fields in admin panel

- Controller/Admin/Order/OrderTabDescriptor.php
- Tests/Unit/Controller/Admin/Order/OrderTabDescriptorTest.php
- Tests/Unit/Controller/Admin/TestDataHelper.php
- menu.xml
- metadata.php
- views/admin/tpl/tab_descriptor.tpl
* Add order descriptor tab in admin panel which contains descriptor from transaction details.
* https://jira.parkside.at/browse/WDPD-185
> WDPD-185 Descriptor order tab

- Tests/Unit/Controller/Admin/TestDataHelper.php
- Tests/Unit/Core/OrderHelperTest.php
- Tests/Unit/Core/ResponseMapperTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
* Adds unit tests
https://jira.parkside.at/browse/WDPD-191
> Increase to 90% Test Coverage

- Core/ResponseMapper.php
* improves the display of the keys in the transaction response details view
* https://jira.parkside.at/browse/WDPD-201
> WDPD-201 Nice display of keys in transaction response details view

- README.md
Add Codacy's code coverage badge to the `README`
> Add Codacy's Code Coverage Badge

- Core/AccountHolderHelper.php
- Extend/Controller/OrderController.php
- Extend/Model/Order.php
- Extend/Model/PaymentGateway.php
- Model/InvoicePaymentMethod.php
- Model/PaymentMethod.php
- Model/PayolutionBtwobPaymentMethod.php
- Tests/Integration/Model/OrderTest.php
- Tests/Unit/Core/AccountHolderHelperTest.php
- Tests/Unit/Model/PayolutionInvoicePaymentMethodTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
- views/blocks/order_button.tpl
Add front end handling of Payolution B2B
- show mandatory company name field if not already provided
- don't show the date of birth field
- check's to show payment method
Activate Payolution B2B and check for proper frontend handling
https://jira.parkside.at/browse/WDPD-194
> WDPD-194 Frontend handling Payolution B2B

- Tests/Unit/Model/PaymentMethodTest.php
- Tests/Unit/Model/PayolutionBtwobPaymentMethodTest.php
adds unit tests for Payolution B2B
adds tests to `PaymentMethodTest.php`
https://jira.parkside.at/browse/WDPD-198
> WDPD-198 Payolution B2B  Add Unit Tests

- Tests/Acceptance/CheckoutTestCase.php
- Tests/Acceptance/PayolutionBtwobCheckoutTest.php
- Tests/Acceptance/PayolutionInvoiceCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
- Tests/Acceptance/inc/mock-data.json
adds Selenium Tests
- Payolution B2C
- Payolution B2B
https://jira.parkside.at/browse/WDPD-198
> WDPD-198 Add Payolution Selenium tests

- Tests/Unit/Model/AlipayCrossBorderPaymentMethodTest.php
> WDPD-192 improve tests

- Core/OxidEeEvents.php
* Improves SEPA Direct Debit Mandate language handling
* Make sure the needed translation files are copied to the corresponding shop directories(https://oxidforge.org/en/language-handling.html)
* Add new languages, check if all strings are translated as expected
https://jira.parkside.at/browse/WDPD-210
> WDPD-210: Improves language handling for SEPA Mandate

- Core/OxidEeEvents.php
- Core/Vault.php
Create the `Vault` table to save credit card information.
https://jira.parkside.at/browse/WDPD-209
> WDPD-209 Create Vault table

- Tests/Integration/Core/VaultTest.php
Create integration tests for the `Vault`
https://jira.parkside.at/browse/WDPD-209
> WDPD-209 Vault table integration tests

- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
- Tests/Unit/Extend/Controller/OrderControllerTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
* Adapt tests to wpp v2 changes
* Base branch: wdpd-207-wpp-seamless
https://jira.parkside.at/browse/WDPD-207
> WDPD-207: WPP v2 Tests

- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
- Tests/Unit/Extend/Controller/OrderControllerTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
> Revert "WDPD-207: WPP v2 Tests"

- Model/CreditCardPaymentMethod.php
- default_payment_config.xml
- translations/de/module_de_lang.php
- translations/en/module_en_lang.php
- translations/fr/module_fr_lang.php
- translations/id/module_id_lang.php
- translations/jp/module_jp_lang.php
- translations/kr/module_kr_lang.php
- translations/zh_CN/module_zh_CN_lang.php
- translations/zh_TW/module_zh_TW_lang.php
- views/admin/de/module_de_lang.php
- views/admin/en/module_en_lang.php
- views/admin/fr/module_fr_lang.php
- views/admin/id/module_id_lang.php
- views/admin/jp/module_jp_lang.php
- views/admin/kr/module_kr_lang.php
- views/admin/zh_CN/module_zh_CN_lang.php
- views/admin/zh_TW/module_zh_TW_lang.php
Add One-click to Credit card's admin panel
https://jira.parkside.at/browse/WDPD-214
> WDPD-214 Credit card One-click backend configuration

- Core/Helper.php
- Extend/Controller/Admin/PaymentMain.php
- Extend/Controller/OrderController.php
- Model/CreditCardPaymentMethod.php
- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
- Tests/Unit/Extend/Controller/OrderControllerTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
- default_payment_config.xml
- out/js/wirecard_wdoxidee_credit_card_form.js
- views/admin/blocks/wd_admin_payment_main_form.tpl
Final Merge PR for wpp v2
https://jira.parkside.at/browse/WDPD-207
> Wdpd 207 base

- Tests/Integration/Model/MetaDataModelTest.php
- Tests/Unit/Model/PaymentMethodTest.php
- Tests/Unit/Model/PayolutionInvoicePaymentMethodTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
Updates unit test for metadata logic (which now has additional field for initial payment title)
https://jira.parkside.at/browse/WDPD-216
> WDPD-216 Update unit tests for initial payment title logic

- Model/PaymentMethod/CreditCardPaymentMethod.php
* Adds credit card payment method initial title on admin panel's configuration page
* Go to Credit Card configuration page in admin panel
* You should see initial payment method title translation above the payment method logo
https://jira.parkside.at/browse/WDPD-224
> WDPD-224 Add Credit Card payment method initial title

- Core/OxidEeEvents.php
- Tests/Integration/Extend/Controller/ThankYouControllerTest.php
- Tests/Integration/Model/OrderTest.php
- Tests/Integration/Model/TransactionTest.php
- Tests/Unit/Controller/NotifyHandlerTest.php
- Tests/Unit/Core/OxidEEEventsTest.php
- Tests/Unit/Extend/Controller/Admin/PaymentMainTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
* add unit tests for cc one-click
* increase test coverage to > 90%
* Do not merge before #189 is merged and the correct base branch is set
https://jira.parkside.at/browse/WDPD-58
> WDPD-215: improve test coverage

- Model/PaymentMethod/CreditCardPaymentMethod.php
* Sets the text color of the delete button to black, to make it visible in azure theme
> WDPD-58: Improve one-click cc delete button for azure theme

- Extend/Controller/OrderController.php
- Extend/Model/PaymentGateway.php
- Model/PaymentMethod/CreditCardPaymentMethod.php
- Model/PaymentMethod/PaymentMethod.php
- Tests/Unit/Extend/Model/PaymentGatewayTest.php
- composer.json
Handle response from form interaction.
https://jira.parkside.at/browse/WDPD-58
> WDPD-58 Handle Credit Card 1-click Response

- composer.lock
update the `composer.lock` file after payment SDK update.
> Update Lock File

- out/js/wirecard_wdoxidee_credit_card_form.js
* Increases the height of the iframe to fit in very small displays
> WDPD-207: Improve iframe size for very small displays

- Core/OxidEeEvents.php
- Model/PaymentMethod/CreditCardPaymentMethod.php
- out/js/wirecard_wdoxidee_credit_card_form.js
> Fixed error with database vault new fields and missing request fields towards wpp
