wirecard/oxid-ee

- Core/OxidEE_Events.php
- default_payment_config.xml
- out/blocks/wd_admin_payment_main_form.tpl
- phpmd.xml
* adds .xml configuration file for Wirecard's payment methods
* adds Wirecard's payment methods defined in default_payment_config.xml on module activation event
* disables all payment methods by default
* Login to the admin
* Go to Extensions → Modules and activate *Wirecard Oxid EE Paymentgateway*
* Go to Payment Methods. You will see all the payment methods which were defined in default_payment_config.xml. By default they are disabled.
https://jira.parkside.at/browse/WDPD-54
> WDPD-54 Configure payment methods

- Core/OxidEE_Events.php
If the module is deactivated we need to disable the payment types as well
In the admin panel:
* activate Wirecard module
* activate 'Wirecard Paypal' payment method
* see that 'Wirecard Paypal' is an option in the shop to pay with
* deactivate the module
* see that Paypal is no longer an option in the shop to pay with
https://jira.parkside.at/browse/WDPD-88
> WDPD-88 Disable payment methods

- .bin/phraseapp/wd-phraseapp.rb
- Core/ResponseHandler.php
- Extend/Controller/ThankYouController.php
- Extend/Core/Email.php
- Extend/Model/Order.php
- metadata.php
- views/blocks/email_html_order_cust_orderemail.tpl
- views/blocks/email_html_order_owner_orderemail.tpl
- views/blocks/email_plain_order_cust_orderemail.tpl
- views/blocks/email_plain_order_owner_orderemail.tpl
- views/blocks/thankyou.tpl
* Adds Extension Settings for enabling/disabling sending pending emails
* For custom payment methods it changes the flow of mails being sent, also adds different wordings into the email body
* Changes the wordings of the last checkout page for customer
* As a merchant:
* In the Master Settings -> Core settings verify the SMTP and email settings
* Enable the Extension Module
* On the settings TAB of modules, check that default settings of sending pending emails is disabled
* Feel free to change this setting
* As a customer ordering with Paypal:
* Perform the order with Paypal Payment method
* Appropriate mails should be received by customer and merchant - if pending state received, extension setting should be taken into account
* As a customer ordering with default payment:
* Perform the …
> WDPD-57 Configure email notification

- Controller/NotifyHandler.php
- Core/OrderHelper.php
- Core/OxidEEEvents.php
- Extend/Controller/OrderController.php
- Extend/Controller/PaymentController.php
- Extend/Model/Order.php
- Model/PaymentMethod.php
- Tests/Integration/Model/OrderTest.php
- Tests/WdUnitTestCase.php
- metadata.php
- translations/de/module_de_lang.php
- translations/en/module_en_lang.php
- views/admin/de/module_de_lang.php
- views/admin/en/module_en_lang.php
* Adds config settings to all payment methods to automatically delete an order if the associated transaction failed or is canceled
* Fixes OXID Unit Tests failing on info logs
* If a transaction is canceled and then a new transaction is made for the same order, the old order is deleted. This is required so that OXID doesn't throw a "Duplicate order" error.
* Go to _Shop Settings → Payment Methods_ and select a Wirecard payment
* Make sure both "Delete Canceled Order" and "Delete Failed Order" is set to "Yes"
* Go to the frontend and make a purchase using the payment method, but don't finish it yet
* In a new tab, go to _Administer Orders → Orders_ and confirm that the order shows up in the table
* Abort the transaction
* Go back to _Administer Orders → Orders_ and confirm that the order …
> WDPD 90: Config Order Delete on Fail/Cancel

- Controller/Admin/ModuleSupport.php
- Controller/Admin/Tab.php
- Controller/Admin/Transaction/TransactionTabPostProcessing.php
- Controller/Admin/TransactionList.php
- Core/Helper.php
- Extend/Core/Email.php
- Extend/ListModel.php
- Extend/Model/PaymentGateway.php
- Extend/ViewConfig.php
- Model/CreditCardPaymentMethod.php
- Model/PaymentMethod.php
- Model/PaypalPaymentMethod.php
- Model/SofortPaymentMethod.php
- Tests/Unit/Core/HelperTest.php
- Tests/Unit/Extend/EmailTest.php
- composer.lock
- menu.xml
- metadata.php
- views/admin/tpl/email/module_support_email.tpl
- views/admin/tpl/module_support.tpl
- views/blocks/wirecard_credit_card_fields.tpl
* Adds new "Module support" tab on the Extensions/Module detail page
* Metadata.php email value is used as recipient of the support email
* Email from and reply to values have defaults from Oxid Master settings -> Core settings -> Info e-mail Address, but can be changed by user
* Login to the admin
* Go to Extensions → Modules and activate _Wirecard Oxid EE Paymentgateway_
* Go to tab _Support_
* Enter the message and send the email
* Jira Ticket [WDPD-89](https://jira.parkside.at/browse/WDPD-89)
* It is the subtask of [WDPD-55](https://jira.parkside.at/browse/WDPD-55)
> WDPD-89 Module support email

- Extend/Model/PaymentGateway.php
* Send Basket info for Sofort / Credit card when **Send additional info** selected
* Original logic is preserved for Paypal
* Respectively enable payment methods and test cases with "Send additional data" selected or not
* [WDPD-118](https://jira.parkside.at/browse/WDPD-118)
> WDPD-118 Change add basket info logic

- Model/CreditCardPaymentMethod.php
- Model/PaymentMethod.php
- Model/PaypalPaymentMethod.php
- Model/SofortPaymentMethod.php
* Reorder Credit Card limits config fields
* Unify order of the payment method fields
* Update the wiki screenshot, because new items are added - Delete Canceled Order, Delete Failed Order
* Go to administration
* In the Credit Card payment method page, check the fields order
> WDPD-34 Reorder payment method edit fields

- views/admin/blocks/admin_payment_main_editor.tpl
* Fix default payment admin page when no payment method is selected
* Log into Admin
* Go to Payment Method settings
* Check the default payment page when no payment method is selected
> WDPD-66 Show chat only if payment is available

- Controller/Admin/Order/OrderTabTransactions.php
- Controller/NotifyHandler.php
- Core/OxidEEEvents.php
- Core/ResponseHandler.php
* Removes the "secure" column from the order transaction tab table
* Go to _Administer Orders → Orders_ and select the _Transactions_ tab
* Verify that the column _Secure_ is not displayed
> WDPD-65: Remove "secure" column from order transactions tab

- Core/OxidEEEvents.php
- default_payment_config.xml
* uses oxsort value for sorting Wirecard payment methods (Credit card is on the first place, and other payment methods are sorted alphabetically).
* Activate the module
* Go to Shop Settings -> Payment Methods
* Wirecard payment methods are now being sorted according to the given rules. Merchant can re-sort them by changing the value of "Sorting". Payment with the lowest value for "Sorting" field comes first on the sorting list.
* https://jira.parkside.at/browse/WDPD-121
> WDPD-121 Add payment method sorting

- Controller/Admin/Order/OrderTab.php
- Controller/Admin/Tab.php
- Controller/Admin/Transaction/TransactionTab.php
- Controller/Admin/Transaction/TransactionTabPostProcessing.php
- Tests/Unit/Controller/Admin/Transaction/TransactionTabPostProcessingTest.php
- views/admin/tpl/tab_post_processing.tpl
- views/admin/tpl/tab_simple.tpl
- views/admin/tpl/tab_table.tpl
* adds the live chat button to the 'Transactions' tab in the orders overview
* improves the display logic of the live chat button in the two transaction management tabs in the orders overview, so it is only shown for orders that were paid with a Wirecard payment method.
* https://jira.parkside.at/browse/WDPD-126
> WDPD-126 Add live chat button to 'Transactions' tab

- Core/PaymentMethodHelper.php
- Extend/Model/PaymentGateway.php
- Model/SepaDirectDebitPaymentMethod.php
* Makes BIC input field in SEPA Direct Debit required in the checkout process.
* PR includes small coding style improvements according to previous feedback.
* https://jira.parkside.at/browse/WDPD-149
> WDPD-149 Make SEPA DD BIC required

- Controller/Admin/Transaction/TransactionTabPostProcessing.php
- Core/Helper.php
- Core/TransactionHandler.php
- Tests/Unit/Core/HelperTest.php
- Tests/Unit/Core/TransactionHandlerTest.php
* improves the floating-point calculation for post-processing transactions by using `bcsub` and an epsilon value for comparison.
* https://jira.parkside.at/browse/WDPD-144
> WDPD-144 Improve floating-point calculation of post-processing transactions

- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/inc/config.json
- Tests/Acceptance/inc/locators.json
* Adds Credit Card checkout tests for purchase/authorization actions
* Adds Credit Card checkout tests for 3d/non-3d authorization
* Run `rake runtests_selenium` and check if all tests succeed
* For information on how to see the Selenium tests being run in the browser, follow the instructions in this PR: https://github.com/wirecard/oxid-ee/pull/79
* WDPD-131: https://jira.parkside.at/browse/WDPD-131
> WDPD-131: Create Selenium Happy Flow Tests for Credit Card

- out/css/wirecard_wdoxidee_common.css
- views/admin/tpl/tab_post_processing.tpl
* adapts the input field type for the post-processing transaction amount from `text` to `number`
* https://jira.parkside.at/browse/WDPD-155
> WDPD-155 Numeric input for post-processing transaction amount

- .bin/generate-tag.sh
- .travis.yml
- Ensures the GitHub API key is passed to the Travis release provider
- Enables the `errexit` option in the tag-generating script
> Update release process

- Core/OrderHelper.php
- Extend/Controller/OrderController.php
- Model/PaymentMethod.php
- Model/SepaDirectDebitPaymentMethod.php
- Tests/Unit/Core/OrderHelperTest.php
- Tests/Unit/Model/SepaDirectDebitPaymentMethodTest.php
- views/blocks/checkout_errors.tpl
- views/blocks/sepa_mandate_modal.tpl
* Adds backend validation for SEPA Direct Debit payments to check whether or not the mandate accept checkbox was actually ticked
* Adds Unit tests to SEPA Direct Debit payment method
* Adds alert styles for the Azure theme
* The error message "Mandate information was not accepted." is deliberately not translated, because it is only displayed to the user if he attempted to manipulate the SEPA form.
* Activate the _Wirecard SEPA Direct Debit_ method
* Go through the checkout process
* On the last step, click "Order now" to open the SEPA mandate popup
* Use your browser's developer tools to run the following command in the console (e.g. for Chrome, press `⎇⌘J`): `document.querySelector('.submitButton[disabled]').removeAttribute('disabled')`
* The "Accept" button should now be activated, even …
> WDPD-154: Prevent SEPA Mandate Button CSS Manipulation

- Core/OxidEeEvents.php
- phpcs/Custom/Sniffs/CodeAnalysis/UnnecessaryImportSniff.php
* Adds a PHPCS sniff to prevent imports within the same namespace
Before the fix:
```php
namespace Wirecard\Oxid\Core;
use Wirecard\Oxid\Core\Helper;
use Wirecard\Oxid\Core\OrderHelper;
use Exception;
use DateTime;
```
After the fix:
```php
namespace Wirecard\Oxid\Core;
use Exception;
use DateTime;
```
* Run `rake cs_check` and/or `rake cs_fix` to check for errors
* Confirm that errors are thrown and fixed correctly
> Add unnecessary import PHPCS sniff

- Model/GiropayPaymentMethod.php
- Tests/Acceptance/GiropayCheckoutTest.php
- default_payment_config.xml
* Renames giropay payment method from **G**iropay to **g**iropay
* Enable the module
* Go to _Shop Settings_ → _Payment Methods_
* Confirm that "Wirecard giropay" is written with a lowercase G
* WDPD-42: https://jira.parkside.at/browse/WDPD-42
> WDPD-42: Rename giropay payment method

- Core/Helper.php
- Core/PaymentMethodHelper.php
- Extend/Controller/Admin/PaymentCountry.php
- Model/RatepayInvoicePaymentMethod.php
- Tests/Unit/Core/HelperTest.php
- Tests/Unit/Core/PaymentMethodHelperTest.php
- Tests/Unit/Extend/Controller/Admin/PaymentCountryTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
- default_payment_config.xml
- metadata.php
- views/admin/blocks/wd_admin_payment_main_form.tpl
* Adds the following settings to the **Guaranteed Invoice by Wirecard** payment method:
* Allowed Shipping Countries
* Allowed Billing Countries
* Identical Billing/Shipping Address
* Disables native OXID country assignment for the **Guaranteed Invoice by Wirecard** payment method
* The default value for shipping- and billing address should be Austria & Germany. This is only possible if the merchant has enabled these countries beforehand (see section "How to Test"). By default, only Germany is enabled.
* The database helper was added because the generic helper class became too big
* The new settings are not processed in the frontend yet
* Enable the module
* Go to _Master Settings_ → _Countries_ and enable some countries – make sure to also enable Austria
* Go to _Shop Settings_ → …
> WDPD-165: Guaranteed Invoice by Wirecard Backend Countries

- Tests/Acceptance/PaypalCheckoutTest.php
* Updates Selenium tests for PayPal to incorporate the latest changes in its UI
* PayPal seems to have some sort of A/B testing in their checkout screens, so sometimes the old version is displayed and sometimes the new one. This could not be pinned down to a specific metric (e.g. IP address or browser language), so the tests are designed to work in both cases.
* Requires https://github.com/wirecard/oxid-ee/pull/124 to be merged first
* Run `rake runtests_selenium` and check if the PayPal tests pass.
> Update PayPal Selenium tests

- composer.json
- composer.lock
* Sets a specific version to the Guzzle dependency to prevent issues with the SDK
This change is needed because a recent update on Guzzle's dev branch caused an error when trying to process a transaction via the SDK (`Invalid header value`), causing all payment requests to fail.
* Activate various payment methods and go through the checkout process
* Confirm that the payments are working again
> Pinned Guzzle version

- Extend/Controller/Admin/PaymentCountry.php
- Model/PayolutionInvoicePaymentMethod.php
- Tests/Unit/Model/PayolutionInvoicePaymentMethodTest.php
- default_payment_config.xml
* Adds the following settings to the **Guaranteed Invoice by Payolution** payment method:
* Allowed Shipping Countries
* Allowed Billing Countries
* Identical Billing/Shipping Address
* Disables native OXID country assignment for the **Guaranteed Invoice by Payolution** payment method
* The default value for shipping- and billing address should be Austria, Germany, Netherlands, Switzerland. This is only possible if the merchant has enabled these countries beforehand (see section "How to Test"). By default, only Germany is enabled.
* Enable the module
* Go to _Master Settings_ → _Countries_ and enable some countries – make sure to also enable Austria, Switzerland and the Netherlands
* Go to _Shop Settings_ → _Payment Methods_ and click on **Guaranteed Invoice by Payolution**
* Confirm that …
> WDPD-174: Guaranteed Invoice by Payolution Backend Countries

- Core/OrderHelper.php
- Core/PaymentMethodFactory.php
- Extend/Controller/OrderController.php
- Extend/Model/Payment.php
- Tests/Acceptance/CashInAdvanceCheckoutTest.php
- Tests/Acceptance/CheckoutTestCase.php
- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/EpsCheckoutTest.php
- Tests/Acceptance/GiropayCheckoutTest.php
- Tests/Acceptance/IdealCheckoutTest.php
- Tests/Acceptance/PaypalCheckoutTest.php
- Tests/Acceptance/RatepayInvoiceCheckoutTest.php
- Tests/Acceptance/SepaDirectDebitCheckoutTest.php
- Tests/Acceptance/SofortCheckoutTest.php
- Tests/Unit/Core/OrderHelperTest.php
- Tests/Unit/Core/PaymentMethodFactoryTest.php
* Resolves an issue that causes the checkout to be broken for default payment methods (i.e. non-Wirecard payment methods)
* Adds Selenium tests for one of OXID's default payments
* Activate the module
* Go through the checkout and select one of OXID's default payment methods, e.g. **Cash in advance**
* Check if the order can be placed without any errors
> Restore default payment methods checkout

- Core/SessionHelper.php
- Model/RatepayInvoicePaymentMethod.php
- Tests/Unit/Core/PaymentMethodFactoryTest.php
- Tests/Unit/Core/PaymentMethodHelperTest.php
- Tests/Unit/Core/SessionHelperTest.php
- Tests/Unit/Model/CreditCardPaymentMethodTest.php
- Tests/Unit/Model/PaypalPaymentMethodTest.php
- Tests/Unit/Model/RatepayInvoicePaymentMethodTest.php
- Tests/Unit/Model/SofortPaymentMethodTest.php
* Applies the following restrictions to whether or not the **Guaranteed Invoice by Wirecard** payment is displayed to the user:
* No digital goods must be part of the shopping basket
* The selected currency must be one of the allowed currencies
* The shipping country must be one of the allowed shipping countries
* The billing country must be one of the allowed billing countries
* If the setting "Identical Billing/Shipping Address" is enabled, shipping and billing county must be the same
* Adds unit tests for the methods introduced in https://github.com/wirecard/oxid-ee/pull/115 to keep 90% code coverage
* Activate the payment method
* Try different settings for:
* Allowed Currencies
* Allowed Shipping Countries
* Allowed Billing Countries
* Check if the restrictions noted above are …
> WDPD 182: Guaranteed Invoice by Wirecard Final Frontend Payment Method

- Model/RatepayInvoicePaymentMethod.php
* Updates the logic by which the **Guaranteed Invoice by Wirecard** payment method is being displayed to the user
* If the setting "Identical Billing/Shipping Address" is activated, the payment method is only displayed if the user ticked the "Use billing address for shipping" checkbox in the checkout
* This is the same logic OXID uses to check if billing and shipping address are the same
* Activate the **Guaranteed Invoice by Wirecard** payment method and make sure the setting for "Use billing address for shipping" is set to "Yes"
* Go through the checkout and confirm that the payment method is only shown if the user ticked the "Use billing address for shipping" in the "Address" step (note that there also other rules by which the payment method is displayed or not, see …
> WDPD-182: Update identical billing & shipping address logic

- Tests/Acceptance/BaseAcceptanceTestCase.php
- Tests/Acceptance/CheckoutTestCase.php
- Tests/Acceptance/CreditCardCheckoutTest.php
- Tests/Acceptance/EpsCheckoutTest.php
- Tests/Acceptance/GiropayCheckoutTest.php
- Tests/Acceptance/IdealCheckoutTest.php
- Tests/Acceptance/PaypalCheckoutTest.php
- Tests/Acceptance/RatepayInvoiceCheckoutTest.php
- Tests/Acceptance/SepaDirectDebitCheckoutTest.php
- Tests/Acceptance/SofortCheckoutTest.php
- Tests/Acceptance/inc/locators.json
* Improves overall stability of Selenium tests, most notably PayPal, Credit Card and Sofort.
* Increases stability for Selenium tests in slow network conditions
* Add retry functionality to PayPal tests to catch possible A/B tests
* On very slow networks, PayPal sometimes redirects to the Dashboard instead of the payment flow
* Run `rake runtests_selenium` and check if all tests pass
* Optional: Throttle your network speed (e.g. by using [this tool](https://stackoverflow.com/questions/9659382/installing-apples-network-link-conditioner-tool)) and re-run the tests
> Improve Selenium tests stability

- Controller/Admin/Transaction/TransactionTab.php
- Controller/Admin/Transaction/TransactionTabAccountHolder.php
- Controller/Admin/Transaction/TransactionTabPaymentDetails.php
- Controller/Admin/Transaction/TransactionTabShipping.php
- Controller/Admin/Transaction/TransactionTabTransactionDetails.php
- phpcs/Custom/Sniffs/OXID/PhpSyntaxSniff.php
* Translates all keys in the Transaction details tabs (except for _Response Details_)
* Updates PHPCS sniff for type hints
* Activate a Wirecard payment method, e.g. _Wirecard PayPal_
* Make a purchase using the above payment method
* Go to _Wirecard Transactions_ → _Transactions_
* Check if all keys for the following tabs are translated:
* Details
* Transaction Details
* Account Owner
* Shipping
* WDPD-151: https://jira.parkside.at/browse/WDPD-151
> WDPD-151: Translate transaction details

- Core/OxidEeEvents.php
- Extend/Model/Order.php
* Sets order state to "cancelled" or "failed" depending on if consumer was redirected to cancel or error redirect url after payment process.
* PR contains many new translation keys, but only one ('wd_order_status_failed') is used in this PR. The other new keys are part of other PRs which were already added to PhraseApp.
* If consumer cancels *PayPal* payment during the payment process (by clicking on “Cancel and return to Wirecard Merchant’s Test Store”), the order status is set to “Cancelled”
* If consumer cancels *eps* payment during the payment process (by clicking on “Zahlung abbrechen”), the order status is set to “Failed”
* This is dependent on which redirect URL was used after the payment process (success, error, or cancel), and it can’t be influenced directly by the module.
* …
> WDPD-187 Set order state after non-success redirect

- Core/OxidEeEvents.php
* Improves loading of default_payment_config.xml file. The file is now loaded via "local" path.
* Activate the module in admin panel.
* All the payment methods from default_payment_config.xml file should be shown in ``Shop Settings -> Payment Methods``
> Use local path for getting payment method config xml file

- Core/OxidEeEvents.php
* Clears the cache on module deactivation event. This is necessary for making the "Shop Settings -> Payment Methods" load properly after deactivating the module (Wirecard payment methods remain in the view, but they are disabled). 
* Activate the module
* Deactivate the module
* Go to "Shop Settings -> Payment Methods"
* The view should load correctly (no maintenance mode)
* https://jira.parkside.at/browse/WDPD-190
> WDPD-190 Clear cache on module deactivation event

- views/blocks/select_payment.tpl
* Places checkout payment method description inside a non-collapsed box
* Activate the module
* Activate any Wirecard's payment method which has checkout fields (for example SEPA Direct Debit)
* Configure payment description (it's a big textarea field on the right side on the payment configuration page)
* Try to create an order on frontend
* On third step (Payment) select Wirecard's payment method whose description was configured in admin panel previously
* Payment description will be shown in blue box within a non-collapsed payment method box
https://jira.parkside.at/browse/WDPD-203
> WDPD-203 Checkout payment description position improvement

- Extend/Controller/Admin/PaymentMain.php
* Fixes issue with saving configuration of Payolution B2B payment method in admin panel.
* Go to Payolution B2B payment method configuration page in admin panel
* Enter valid configuration data and click on save button
* Configuration is saved successfully
https://jira.parkside.at/browse/WDPD-225
> WDPD-225 Enable saving Payolution B2B configuration changes on admin page

- Controller/NotifyHandler.php
- Core/OrderHelper.php
- Core/OxidEeEvents.php
- Extend/Controller/Admin/PaymentCountry.php
- Extend/Controller/Admin/PaymentMain.php
- Extend/Model/PaymentGateway.php
* credit card transactions (for 3d and non 3d) are stored in db after a success notification
* without a success notification the transaction state will not be success and the order state will not be paid anymore
* every payment method should work as usual
* cc payment method behaviour should be updated to above behaviour
https://jira.parkside.at/browse/WDPD-221
> WDPD-221: Improve credit card payment flow

- Extend/Controller/Admin/PaymentMain.php
- Model/PaymentMethod/AlipayCrossBorderPaymentMethod.php
- out/js/wirecard_wdoxidee_credit_card_form.js
- translations/de/module_de_lang.php
- translations/en/module_en_lang.php
- translations/fr/module_fr_lang.php
- translations/id/module_id_lang.php
- translations/jp/module_jp_lang.php
- translations/kr/module_kr_lang.php
- translations/zh_CN/module_zh_CN_lang.php
- translations/zh_TW/module_zh_TW_lang.php
- views/admin/blocks/wd_admin_payment_main_form.tpl
- views/admin/de/module_de_lang.php
- views/admin/en/module_en_lang.php
- views/admin/fr/module_fr_lang.php
- views/admin/id/module_id_lang.php
- views/admin/jp/module_jp_lang.php
- views/admin/kr/module_kr_lang.php
- views/admin/zh_CN/module_zh_CN_lang.php
- views/admin/zh_TW/module_zh_TW_lang.php
* Adds a TODO for Alipay 
* Adds the new string for cc config errors
* Improves cc iframe height for mobile & desktop
* The bottom space of the credit card iframe should be the same for mobile and desktop
* Check the error messages for credit card and other payment methods after trying to save a invalid configuration, for credit cards the new string should appear, for all other payment methods nothing should change
> WDPD-207 Improve Credit Card UX

- Controller/Admin/Transaction/TransactionTabPostProcessing.php
- Controller/NotifyHandler.php
- Core/ResponseHandler.php
- Model/PaymentMethod/BasePoiPiaPaymentMethod.php
- Model/Transaction.php
- Tests/Integration/Model/TransactionTest.php
- views/admin/tpl/transaction_list.tpl
* Adds POI/PIA transaction which comes via notification, even if it does not correspond to any order
* POI/PIA transactions without order reference are marked as unmatched
* Make a payment using POI or PIA payment method (optionally)
* Fake deposit transaction via Postman (use last example from [here](https://doc.wirecard.com/API_POIPIA.html#API_POIPIA_Samples): it is enough to use any random transaction id, which does not already exist in order database)
* In admin panel, go to ```Wirecard Transactions -> Transactions```
* Unmatched transactions are labeled like that in "Transaction state" column
* It is assumed that POI/PIA payment methods are called "wiretransfer" inside deposit notification
https://jira.parkside.at/browse/WDPD-239
> WDPD-239 Change unmatched transactions handling

- views/blocks/order_button.tpl
* Hides Sepa Direct Debit modal on initial order page load via inline style rule. This was normally done in wirecard_wdoxidee_modal.css, but in a certain situations it can happen that css was not loaded, and therefore modal was not hidden by default.
* Try to make a payment on frontend using Sepa Direct Debit and any other payment method. Sepa Direct Debit modal will not be loaded, until clicking on "Order Now" button in the case of Sepa Direct Debit payment method.
* https://jira.parkside.at/browse/WDPD-240
> WDPD-240 Hide Sepa Direct Debit modal on order page

- out/js/wirecard_wdoxidee_credit_card_form.js
* Gets browser width instead of screen width before selecting credit card form height.
* Try to make a purchase using Wirecard Credit Card payment method.
* On the last step of the checkout process, credit card form height should be 220px on desktop, and 410 on mobile screen, and it should not overlap with terms and condition under it.
* https://jira.parkside.at/browse/WDPD-241
> WDPD-241 Get correct browser width for rendering credit card form

- out/js/wirecard_wdoxidee_credit_card_form.js
The top order button does not trigger `submitPaymentForm` and thus does not work correctly.  
This commit adds the necessary click handler to the button.
> Fix top order button for credit card

- Extend/Model/PaymentGateway.php
Although the methods description says otherweise `_addDescriptor` is currently not overridable since its visibility is `private` and is called with the `self` keyword.
> Allow overriding _addDescriptor
